"""Add audio analysis table

Revision ID: d67928b05f5f
Revises: 57dcc58d19d2
Create Date: 2025-12-25 00:24:50.141890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67928b05f5f'
down_revision = '57dcc58d19d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('rms_mean', sa.Float(), nullable=True),
    sa.Column('spectral_centroid_mean', sa.Float(), nullable=True),
    sa.Column('mfcc', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_analysis')
    # ### end Alembic commands ###
