"""Add waveform and fft data

Revision ID: df92c773c87c
Revises: d67928b05f5f
Create Date: 2025-12-25 00:53:29.075202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df92c773c87c'
down_revision = 'd67928b05f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waveform', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('fft', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analysis', schema=None) as batch_op:
        batch_op.drop_column('fft')
        batch_op.drop_column('waveform')

    # ### end Alembic commands ###
